config/routes.rb
Rails.application.routes.draw do
  resources :products

  root 'home#index'
end

app/models/color.rb
class Color < ActiveRecord::Base
  validates :name, presence: true
end

app/models/product.rb
class Product < ActiveRecord::Base
  validates :name, presence: true, length: { maximum: 100 }
  validates :description, presence: true, length: { maximum: 512 }

  has_many :product_variations, dependent: :destroy

  accepts_nested_attributes_for :product_variations,
    allow_destroy: true,
    reject_if: :all_blank

  validates :product_variations, presence: true
end

app/models/product_variation.rb
class ProductVariation < ActiveRecord::Base
  belongs_to :product
  belongs_to :color
  belongs_to :size

  validates :quantity, presence: true
end

app/models/size.rb
class Size < ActiveRecord::Base
  validates :name, presence: true
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def new
    @product = Product.new
    @product.product_variations.build
  end

  def show
    @product = find_product(params[:id])
  end

  def create
    @product = Product.create(product_params)

    respond_with @product
  end

  def edit
    @product = find_product(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    @product.update_attributes(product_params)

    respond_with @product
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_with @product
  end

  private

  def find_product(id)
    Product
      .joins(product_variations: [:color, :size])
      .includes(product_variations: [:color, :size])
      .find(id)
  end

  def product_params
    params
      .require(:product)
      .permit(
        :name,
        :description,
        product_variations_attributes: [:id, :color_id, :size_id, :quantity, :_destroy]
      )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_menu_helper.rb
module MainMenuHelper

  def main_menu
    content_tag :ul, class: 'nav navbar-nav' do
      resources.map do |resource|
        concat build_item(resource)
      end
    end
  end

  private

  def build_item(resource)
    content_tag :li, class: active_class(resource.first) do
      link_to I18n.t("main_menu.#{resource.first}"), resource.last
    end
  end

  def resources
    {
      products: products_path
    }
  end

  def active_class(resource_name)
    'active' if controller_name == resource_name.to_s
  end
end

app/helpers/pages_helper.rb
module PagesHelper
  def page_header(title)
    content_tag :div, class: 'page-header' do
      content_tag :h1 do
        concat title
        concat align_right { yield } if block_given?
      end
    end
  end

  def button_new(path)
    link_to path, class: 'btn btn-primary' do
      concat content_tag :i, ' ', class: 'glyphicon glyphicon-plus'
      concat I18n.t('buttons.new')
    end
  end

  def button_edit(path)
    link_to path, class: 'btn btn-default' do
      concat content_tag :i, ' ', class: 'glyphicon glyphicon-edit'
      concat I18n.t('buttons.edit')
    end
  end

  def button_back(path)
    link_to path, class: 'btn btn-default' do
      concat content_tag :i, ' ', class: 'glyphicon glyphicon-chevron-left'
      concat I18n.t('buttons.back')
    end
  end

  def button_destroy(path)
    link_to path, class: 'btn btn-danger', method: :delete, data: { confirm: I18n.t('messages.are_you_sure') } do
      concat content_tag :i, ' ', class: 'glyphicon glyphicon-trash'
      concat I18n.t('buttons.destroy')
    end
  end

  def align_right
    content_tag :div, class: 'pull-right' do
      yield
    end
  end
end

app/views/home/index.html.erb
<center>
  <h2><%= t('messages.welcome') %></h2>
  <%= image_tag 'product_manager.jpg', class: 'img-responsive' %>
</center>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <div class="navbar-collapse collapse in" aria-expanded="true" style="">
        <%= main_menu %>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Teste Synergia Rails</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render partial: 'layouts/header' %>

  <div class="container-fluid">
    <%= yield %>
  </div>

  <br />
</body>
</html>

app/views/products/_form.html.erb
<%= simple_form_for @product do |f| %>
  <%= f.error_notification %>

  <div class="row">
    <div class="col-lg-6 col-md-6 col-sm-12">
      <%= f.input :name %>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-6 col-md-6 col-sm-12">
      <%= f.input :description, as: :text %>
    </div>
  </div>

  <h3><%= @product.product_variations.model_name.human(count: 2) %></h3>

  <div id="product_variations">
    <%= f.simple_fields_for :product_variations do |ff| %>
      <%= render 'product_variation_fields', f: ff %>
    <% end %>
  </div>

  <br />

  <div class="form-actions">
    <%= link_to_add_association(
      t('buttons.add', record: @product.product_variations.model_name.human(count: 1)),
      f,
      :product_variations,
      :class => "btn btn-default"
    ) %>
    <%= f.button :submit, class: 'btn btn-primary ' %>
  </div>
<% end %>

app/views/products/_product_variation_fields.html.erb
<div class="row nested-fields">
  <div class="col-lg-2 col-md-2 col-sm-3">
    <%= f.association :color %>
  </div>

  <div class="col-lg-2 col-md-2 col-sm-3">
    <%= f.association :size %>
  </div>

  <div class="col-lg-2 col-md-2 col-sm-3">
    <%= f.input :quantity %>
  </div>

  <div class="col-lg-2 col-md-2 col-sm-6">
    <br />

    <%= link_to_remove_association t('buttons.remove'), f  %>
  </div>
</div>

app/views/products/edit.html.erb
<%=
  page_header(t('titles.edit', record: @product.model_name.human(count: 1))) do
    button_back(products_path)
  end
%>

<%= render 'form' %>

app/views/products/index.html.erb
<%=
  page_header(@products.model_name.human(count: 2)) do
    button_new(new_product_path)
  end
%>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= Product.human_attribute_name(:name) %></th>
      <th class="col-md-1"><%= %></th>
    </tr>
  </thead>

  <tbody>
    <%- @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td>
          <%= link_to ' ', product_path(product), class: 'glyphicon glyphicon-eye-open' %>
          <%= link_to ' ', edit_product_path(product), class: 'glyphicon glyphicon-edit' %>
        </td>
      </tr>
    <%- end %>
  </tbody>
</table>

app/views/products/new.html.erb
<%=
  page_header(t('titles.new', record: @product.model_name.human(count: 1))) do
    button_back(products_path)
  end
%>

<%= render 'form' %>

app/views/products/show.html.erb
<%=
  page_header(@product.model_name.human(count: 2)) do
    concat button_back(products_path)
    concat button_edit(edit_product_path(@product))
    concat button_destroy(product_path(@product))
  end
%>

<div class="row">
  <div class="col-md-12 col-lg-12 col-sm-12">
    <b><%= Product.human_attribute_name(:name) %>: </b>
    <%= @product.name %>
  </div>

  <div class="col-md-12 col-lg-12 col-sm-12">
    <b><%= Product.human_attribute_name(:description) %>: </b>
    <%= @product.description %>
  </div>
</div>

<br />

<div class="row">
  <div class="col-md-12 col-lg-12 col-sm-12">
    <table class="table table-striped">
      <thead>
        <tr>
          <th><%= ProductVariation.human_attribute_name(:color) %></th>
          <th><%= ProductVariation.human_attribute_name(:description) %></th>
          <th><%= ProductVariation.human_attribute_name(:quantity) %></th>
        </tr>
      </thead>

      <tbody>
        <%- @product.product_variations.each do |variation| %>
          <tr>
            <td><%= variation.color.name %></td>
            <td><%= variation.size.name %></td>
            <td><%= variation.quantity %></td>
          </tr>
        <%- end %>
      </tbody>
    </table>
  </div>
</div>